### PR TITLE
Update for ecto 2.2

### PR DESCRIPTION
**Pull request by mfb2**
Hi Jeff!

Finally got around to starting some of the code changes for Ecto 2.2 ( Issue #19 ).  I've learned that Ecto 3.0 will break this again, though it may be a little easier to manage on the next round.

In this PR, there are two main changes being introduced:

1.  A slight refactor of the `Adapter` code itself.  The module was getting pretty big and it felt like it could use a touch of dissecting.  To that end, I moved the `loaders` and `dumpers` to separate files, as well as some of the conversion functions.

2.  Fixed retrievals.  As it turns out, there's a bunch more magic available from the converter function passed in to `execute`, so it was a matter of clearing the cruft and letting it do it's job.

Updates are still broken at the moment.  For some reason, the calls to `TestRepo` aren't making their way into the adapter.  I haven't found the root cause yet, so I'm hoping maybe another pair of eyes might help.

Please let me know your thoughts, I'm happy to address any feedback you may have.

Cheers!!

### CODE REVIEW

**Comment by mfb2** [comment]
Looks like I got the lingering `update` issues resolved.  I'm in the process of integration testing and once it's complete, I'll advise of the results.

**Comment by mfb2** [comment]
Ran the tests, looks like we're back to parity.  Give it a whirl and let me know what you think.

**Review by jeffweiss — APPROVED** [review]
Thanks, Manny!

**Comment by jeffweiss** [comment]
Merged via 6b0d5f5

**Pull request closed without merging**
